# Generated by Django 2.2.10 on 2021-12-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizreport',
            name='user_id',
        ),
        migrations.AddField(
            model_name='quizreport',
            name='user_poiter_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
