# Generated by Django 2.2.10 on 2021-12-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211228_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
