# Generated by Django 2.2.10 on 2021-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20211228_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.BigIntegerField(null=True),
        ),
    ]
