# Generated by Django 2.2.10 on 2021-12-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20211228_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_choise',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(max_length=11),
        ),
    ]
